spring.application.name=base-jpa-repo
spring.datasource.password=postgres
spring.datasource.url=jdbc:postgresql://localhost:5432/base_jpa_repo
spring.datasource.username=postgres
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.show-sql=true