spring:
  datasource:
    reader:
      url: jdbc:postgresql://localhost:5432/spring_reader
      username: postgres
      password: postgres
    writer:
      url: jdbc:postgresql://localhost:5432/spring_writer
      username: postgres
      password: postgres
  application:
    name: jpa-reader-writer-ds
